[target.wasm32-unknown-unknown]
linker = "C:\\Program Files\\LLVM\\clang+llvm-22.1.8-x86_64-pc-windows-msvc\\bin\\wasm-ld.exe"
rustflags = ["-C", "link-arg=--export-memory", "-C", "link-arg=-zstack-size=1048576", "-C", "link-arg=--stack-first", "-C", "link-arg=--no-entry", "-C", "link-arg=--strip-all", "-C", "link-arg=--gc-sections"]