// ============================================================================
// EXECUTABLE CONTRACT — the AR page's dictionary vs its EN sister file
// ----------------------------------------------------------------------------
// v0.5.28 pinned the AR page's own dictionary (277 keys, a bijection against its
// own markup) and left one thing explicitly unguarded: whether the EN sister
// `coreguard-gate41-visual-en.html` actually renders what that dictionary's `en`
// side says. Two files, one message, nothing comparing them.
//
// Measured before writing this, so the contract states facts rather than hopes:
//
//   * All 277 dictionary `.en` values appear VERBATIM in the sister (0 absent).
//     The cross-file link is real and it holds.
//   * The two DOM skeletons are NOT identical, and must not be asserted to be.
//     The AR page is the interactive twin (it carries the language switcher);
//     the sister is the printable twin (it carries a printhead + print button).
//     That is why the tag counts differ by exactly one each of b/span/div -
//     and [C5] already recorded the cause: the dictionary was generated by a
//     lockstep DOM walk with the EN `printhead` subtree dropped first.
//
// So the invariant is NOT "the files are identical". It is the narrower set of
// things that must never drift, plus an EXPLICIT pin on the two intended
// asymmetries - so a future session neither "fixes" a deliberate difference nor
// lets a real one hide among them.
// ============================================================================

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, "..", "..");
const AR_REL = "docs/coreguard-gate41-visual.html";
const EN_REL = "docs/coreguard-gate41-visual-en.html";

const ar = readFileSync(join(REPO, AR_REL), "utf8");
const en = readFileSync(join(REPO, EN_REL), "utf8");

// The AR page's runtime dictionary, brace-matched out of its source.
function extractDictionary() {
  const m = /(?:var|const|let)\s+D\s*=\s*\{/.exec(ar);
  assert.ok(m, "the AR page no longer declares the runtime dictionary `D`");
  let i = m.index + m[0].length;
  let depth = 1;
  const start = i;
  while (i < ar.length && depth > 0) {
    const c = ar[i];
    if (c === "{") depth++;
    else if (c === "}") depth--;
    i++;
  }
  assert.ok(depth === 0, "the dictionary literal is unbalanced - brace matching ran off the end");
  return eval("({" + ar.slice(start, i - 1) + "})");
}
const entryKeys = Object.keys(extractDictionary().nodes || {});

// Only three named entities exist in these two files today. Decode exactly
// those, and FAIL LOUD on any new one: silently leaving `&nbsp;` undecoded
// would make every string comparison in this file quietly wrong, and a
// comparison that is quietly wrong is worse than no comparison.
const ENTITIES = { lt: "<", gt: ">", amp: "&" };
function decode(s) {
  const stray = [...s.matchAll(/&([a-zA-Z][a-zA-Z0-9]*);/g)].map((m) => m[1]).filter((n) => !(n in ENTITIES));
  assert.deepEqual([...new Set(stray)], [], `new HTML entity/ies - extend ENTITIES: ${[...new Set(stray)].join(", ")}`);
  return s.replace(/&(lt|gt|amp);/g, (_, n) => ENTITIES[n]);
}

// Visible text: tags dropped, entities decoded, whitespace collapsed. Used on
// both sides so a `&amp;` and a literal `&` compare equal.
const text = (s) => decode(s.replace(/<[^>]*>/g, " ")).replace(/\s+/g, " ").trim();
const withoutBlocks = (s) => s.replace(/<script[\s\S]*?<\/script>/gi, " ").replace(/<style[\s\S]*?<\/style>/gi, " ");

const count = (s, tag) => (withoutBlocks(s).match(new RegExp("<" + tag + "\\b", "gi")) || []).length;
const ids = (s) => [...withoutBlocks(s).matchAll(/\sid\s*=\s*"([^"]*)"/g)].map((m) => m[1]);
const textRuns = (s) => [...withoutBlocks(s).matchAll(/>([^<>]+)</g)].map((m) => m[1]).map((t) => t.trim()).filter(Boolean);

test("the EN sister renders every English string the AR dictionary carries", () => {
  // The load-bearing cross-file claim, in both directions:
  //   - an .en the sister never shows means the dictionary is writing dead text
  //   - (the reverse, an .en with no dictionary entry, is gate41-visual-i18n's job)
  const sisterText = text(en);
  const absent = entryKeys.filter((k) => {
    const v = text(extractDictionary().nodes[k].en);
    return v.length > 0 && !sisterText.includes(v);
  });
  assert.deepEqual(
    absent,
    [],
    `dictionary .en strings the sister never renders (${absent.length}/${entryKeys.length}): ` +
      absent.slice(0, 5).map((k) => `${k}=${JSON.stringify(text(extractDictionary().nodes[k].en).slice(0, 60))}`).join(" | ")
  );
  assert.equal(entryKeys.length, 277, `dictionary entry count changed: ${entryKeys.length}`);
});

test("the load-bearing structure is identical in both files", () => {
  // Counts of the elements that carry the page's meaning. A section, a table
  // row or a heading that exists in one twin and not the other means the
  // sister is a stale snapshot of a different revision - the classic silent
  // divergence, and invisible to any per-file test.
  const expected = {
    section: 10, h1: 1, h2: 10, h3: 12, h4: 5,
    table: 4, thead: 4, tbody: 4, tr: 30,
    ul: 5, li: 10, a: 14, p: 19, button: 3,
  };
  const drift = Object.entries(expected)
    .filter(([tag, n]) => count(ar, tag) !== n || count(en, tag) !== n)
    .map(([tag, n]) => `<${tag}> AR=${count(ar, tag)} EN=${count(en, tag)} (expected ${n} in both)`);
  assert.deepEqual(drift, [], `structural drift between the twins: ${drift.join("; ")}`);
  assert.equal(ids(en).length, ids(ar).length, `id count diverged: AR=${ids(ar).length} EN=${ids(en).length}`);
  assert.equal(ids(en).length, 34, `id count changed: ${ids(en).length}`);
});

test("the only structural differences are the two intended ones", () => {
  // Every tag is compared for parity, and the EN sister is allowed to exceed
  // the AR page on exactly three of them - each by one - because the sister
  // carries a `printhead` block the AR page does not ([C5]: the dictionary walk
  // dropped the EN printhead subtree first). Pinning the SET means a new
  // divergence cannot hide beside a sanctioned one, and a sanctioned one
  // cannot be dropped silently either.
  const TAGS = ["html", "head", "body", "nav", "main", "header", "footer", "div", "span", "p", "a", "b", "bdi",
    "code", "pre", "em", "strong", "i", "small", "ul", "ol", "li", "dl", "dt", "dd",
    "h1", "h2", "h3", "h4", "h5", "h6", "table", "thead", "tbody", "tfoot", "tr", "th", "td", "caption",
    "section", "article", "aside", "figure", "img", "button", "hr", "br", "label", "input", "select", "option"];
  const allowed = { b: 1, span: 1, div: 1 };
  const unexpected = [];
  for (const tag of TAGS) {
    const d = count(en, tag) - count(ar, tag);
    if (d === 0) continue;
    if (allowed[tag] === d) continue;
    unexpected.push(`<${tag}> differs by ${d > 0 ? "+" : ""}${d} (AR=${count(ar, tag)} EN=${count(en, tag)})`);
  }
  assert.deepEqual(unexpected, [], `unexplained structural divergence: ${unexpected.join("; ")}`);
  // and the sanctioned ones must still be exactly the sanctioned ones
  for (const [tag, n] of Object.entries(allowed)) {
    assert.equal(count(en, tag) - count(ar, tag), n, `the sanctioned <${tag}> difference is no longer +${n} - re-measure before re-pinning`);
  }
  assert.match(en, /class="printhead"/, "the EN printhead is gone - the sanctioned +1 b/span/div now has no cause");
});

test("the sister stays dictionary-free", () => {
  // It is the printable twin: literal English, no runtime dictionary, so it
  // cannot drift from the AR page by re-rendering. A second dictionary here
  // would be a second source of truth - exactly what [C27] warns about.
  assert.equal((en.match(/data-i18n/g) || []).length, 0, "the EN sister grew data-i18n attributes - two sources of truth");
  assert.equal((en.match(/D\.nodes/g) || []).length, 0, "the EN sister grew a D.nodes dictionary");
  assert.equal((en.match(/function\s+L\s*\(/g) || []).length, 0, "the EN sister grew an L() resolver");
  // its one script block is the print behaviour, and that is legitimate
  assert.ok(/printhead|window\.print/.test(en), "the sister's print behaviour is gone - the script block was removed or replaced");
});

test("the sister leaks no Arabic", () => {
  // [C5] required the EN side to contain zero Arabic characters. Measured over
  // every text run, not a single sampled one.
  const ARABIC = /[\u0600-\u06FF]/;
  const runs = textRuns(en);
  const leaked = runs.filter((t) => ARABIC.test(t));
  assert.deepEqual(leaked.slice(0, 5), [], `the EN sister shows Arabic in ${leaked.length} run(s): ${JSON.stringify(leaked.slice(0, 3))}`);
  assert.equal(leaked.length, 0, `${leaked.length} text runs in the EN sister contain Arabic`);
  assert.ok(runs.length > 500, `the sister has only ${runs.length} text runs - a parse regression would make the check vacuous`);
});

test("each twin declares its own language and direction", () => {
  // The one attribute pair that is SUPPOSED to differ. Bidi is a correctness
  // property, not cosmetics: a wrong dir silently reverses the rendered order
  // of the whole board while every text assertion still passes.
  assert.match(ar, /<html[^>]*\blang="ar"/, "the AR page no longer declares lang=\"ar\"");
  assert.match(ar, /<html[^>]*\bdir="rtl"/, "the AR page no longer declares dir=\"rtl\"");
  assert.match(en, /<html[^>]*\blang="en"/, "the EN sister no longer declares lang=\"en\"");
  assert.match(en, /<html[^>]*\blang="en"[^>]*\bdir="ltr"/, "the EN sister no longer declares dir=\"ltr\" after lang");
});

test("the intended role asymmetry is pinned on both sides", () => {
  // The AR page switches language; the sister prints. Stated as facts so a
  // future session does not "fix" the difference, and so neither control can
  // rot into a dead button without a test noticing.
  assert.match(ar, /id="langBtn"/, "the AR page lost its language switcher");
  assert.doesNotMatch(en, /id="langBtn"/, "the EN sister must not carry a language switcher - it has nothing to switch to");
  assert.match(en, /id="printBtn"/, "the EN sister lost its print control");
  assert.doesNotMatch(ar, /id="printBtn"/, "the AR page must not carry the print-only control - that is the sister's role");
  const arIds = ids(ar);
  const enIds = ids(en);
  assert.deepEqual(arIds.filter((i) => !enIds.includes(i)), ["langBtn"], "the AR page's id set changed beyond the declared switcher");
  assert.deepEqual(enIds.filter((i) => !arIds.includes(i)), ["printBtn"], "the sister's id set changed beyond the declared print button");
});

test("the AR page still renders with JavaScript disabled", () => {
  // The dictionary is the SWITCHER's payload, not the page's only source of
  // Arabic: 221 of the 277 .ar values are already literal Arabic in the static
  // markup. Stripping that literal text would leave a page that renders
  // nothing without JS - a silent availability regression that every
  // dictionary-level assertion here would happily pass.
  const sIdx = ar.lastIndexOf("<script", ar.indexOf('"nodes"'));
  assert.ok(sIdx > 0, "the dictionary script was not found - cannot measure the no-JS fallback");
  const staticText = text(ar.slice(0, sIdx));
  const nodes = extractDictionary().nodes;
  const literal = entryKeys.filter((k) => {
    const v = text(nodes[k].ar);
    return v.length > 12 && staticText.includes(v);
  });
  assert.equal(
    literal.length,
    221,
    `no-JS fallback changed: ${literal.length}/277 .ar values are literal in the static markup (was 221). Falling means the AR page now depends on JS to render.`
  );
});
